param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
)

$ErrorActionPreference = "Stop"
$RemovedProfileStep = "klipper" + "-profiles"
$RemovedConfigVerifyToggle = "TREED_VERIFY" + "_CONFIG"

function Assert-Contains {
  param(
    [string]$Path,
    [string]$Pattern,
    [string]$Message
  )

  $content = Get-Content -Encoding UTF8 -LiteralPath (Join-Path $RepoRoot $Path) -Raw
  if ($content -notmatch $Pattern) {
    throw "FAIL: $Message ($Path)"
  }
}

function Assert-NotContains {
  param(
    [string]$Path,
    [string]$Pattern,
    [string]$Message
  )

  $content = Get-Content -Encoding UTF8 -LiteralPath (Join-Path $RepoRoot $Path) -Raw
  if ($content -match $Pattern) {
    throw "FAIL: $Message ($Path)"
  }
}

function Read-RepoFile {
  param([string]$Path)

  Get-Content -Encoding UTF8 -LiteralPath (Join-Path $RepoRoot $Path) -Raw
}

function Get-CfgValue {
  param(
    [string]$Path,
    [string]$Key
  )

  $content = Read-RepoFile $Path
  $match = [regex]::Match($content, "(?m)^\s*$([regex]::Escape($Key)):\s*([A-Za-z0-9_.:-]+)\s*$")
  if (-not $match.Success) {
    throw "FAIL: cannot read $Key from $Path"
  }
  $match.Groups[1].Value
}

$MainMcuProfileUuid = Get-CfgValue "klipper/profiles/treed_v2_corexy_v1/mcu_main_octopus_can.cfg" "canbus_uuid"
$MainMcuProfileIface = Get-CfgValue "klipper/profiles/treed_v2_corexy_v1/mcu_main_octopus_can.cfg" "canbus_interface"
$EbbProfileUuid = Get-CfgValue "klipper/profiles/treed_v2_corexy_v1/ebb42_can.cfg" "canbus_uuid"
$EddyProfileUuid = Get-CfgValue "klipper/profiles/treed_v2_corexy_v1/probe_eddy_duo.cfg" "canbus_uuid"
$EddyProfileIface = Get-CfgValue "klipper/profiles/treed_v2_corexy_v1/probe_eddy_duo.cfg" "canbus_interface"

Assert-Contains ".github/workflows/contracts.yml" "tools/tests/\*\*" "GitHub Actions watches contract tests"
Assert-Contains ".github/workflows/contracts.yml" "PowerShell contract tests" "GitHub Actions runs PowerShell contract tests"
Assert-Contains "VERSION" '^\d+\.\d+\.\d+\s*$' "treed-mainshellOS has a semver VERSION file"
Assert-Contains ".github/workflows/release.yml" 'tags:\s*\r?\n\s+- "v\*\.\*\.\*"' "release workflow runs from semver tags"
Assert-Contains ".github/workflows/release.yml" 'MAIN_SHELL_VERSION="\$\(tr -d' "release workflow reads VERSION as the release source"
Assert-Contains ".github/workflows/release.yml" 'EXPECTED_TAG="v\$\{MAIN_SHELL_VERSION\}"' "release workflow maps VERSION to v-prefixed release tag"
Assert-Contains ".github/workflows/release.yml" 'Shell syntax' "release workflow runs shell syntax checks"
Assert-Contains ".github/workflows/release.yml" 'bash -n "\$file"' "release workflow validates shell scripts before packaging"
Assert-Contains ".github/workflows/release.yml" 'Python syntax' "release workflow runs Python syntax checks"
Assert-Contains ".github/workflows/release.yml" 'python3 -m py_compile moonraker/components/\*\.py' "release workflow compiles Moonraker components before packaging"
Assert-Contains ".github/workflows/release.yml" 'treed-mainshellos-release\.json' "release workflow publishes a machine-readable release manifest"
Assert-Contains ".github/workflows/release.yml" '--repo "\$\{GITHUB_REPOSITORY\}"' "release workflow publishes into the current printer-core repository"
Assert-Contains ".github/workflows/README.md" 'release.yml' "workflow docs include the mainshellOS release workflow"
Assert-NotContains "moonraker/base/00-core.conf" '192\.168\.0\.0/16' "Moonraker must not trust the whole LAN"
Assert-Contains "loader/steps/mainsail-web.sh" 'location \^~ /server/treed/' "nginx must isolate TreeD host endpoints"
Assert-Contains "loader/steps/mainsail-web.sh" 'allow 127\.0\.0\.1;' "TreeD host endpoints must allow local kiosk access"
Assert-Contains "loader/steps/mainsail-web.sh" 'deny all;' "TreeD host endpoints must deny LAN clients"
Assert-Contains "loader/steps/mainsail-web.sh" 'proxy_set_header X-Real-IP \\\$remote_addr;' "nginx must forward real client IP to Moonraker"
Assert-Contains "loader/steps/mainsail-web.sh" 'proxy_set_header X-Forwarded-For \\\$proxy_add_x_forwarded_for;' "nginx must forward client chain to Moonraker"
Assert-Contains "moonraker/base/00-core.conf" '\[treed_update\]' "Moonraker base config registers TreeD update component"
Assert-Contains "moonraker/components/treed_update.py" '/server/treed/update/status' "TreeD update component exposes status endpoint"
Assert-Contains "moonraker/components/treed_update.py" '/server/treed/update/check' "TreeD update component exposes check endpoint"
Assert-Contains "moonraker/components/treed_update.py" '/server/treed/update/apply' "TreeD update component exposes apply endpoint"
Assert-Contains "loader/steps/moonraker-config.sh" 'treed-update-apply' "Moonraker config deploys the root-side TreeD updater command"
Assert-Contains "loader/steps/moonraker-config.sh" '/etc/sudoers\.d/treed-update' "Moonraker config installs restricted sudoers rule for TreeD updater"
Assert-Contains "loader/steps/moonraker-config.sh" 'ensure_moonraker_allowed_service "treed-shell"' "Moonraker may restart only the local TreeD Shell UI service"
Assert-Contains "runtime-scripts/treed-update/treed-update-apply" 'TREED_DEPLOY_MODE=auto TREED_NONINTERACTIVE=1 bash install\.sh' "TreeD updater reuses the штатный loader install flow"
Assert-Contains "moonraker/components/treed_update.py" 'targetId' "TreeD update API selects an explicit release target"
Assert-Contains "runtime-scripts/treed-update/treed-update-apply" 'TARGET_ID="\$\{1:-\}"' "TreeD updater accepts target id as its first argument"
Assert-Contains "runtime-scripts/treed-update/treed-update-apply" 'TARGET_TAG="\$\{2:-\}"' "TreeD updater accepts target tag as its second argument"
Assert-Contains "bootstrap-pi.sh" 'https://github\.com/TreeD-Hub/printer-core\.git' "Pi bootstrap clones printer-core"
Assert-NotContains "bootstrap-pi.sh" 'TreeD-Hub/treed-mainshellOS\.git' "Pi bootstrap no longer clones the legacy repository name"
Assert-Contains "bootstrap-pi.sh" 'REPO_DIR="\$\{REPO_DIR:-\$\{BASE\}/printer-core\}"' "Pi bootstrap uses the canonical printer-core checkout path"
Assert-NotContains "bootstrap-pi.sh" 'REPO_DIR="\$\{REPO_DIR:-\$\{BASE\}/treed-mainshellOS\}"' "Pi bootstrap no longer defaults to the legacy checkout path"
Assert-Contains "loader/steps/moonraker-config.sh" 'TREED_UPDATE_REPO_DIR="\$\{PI_HOME\}/treed/printer-core"' "Moonraker config deploys the canonical printer-core updater path"
Assert-Contains "moonraker/base/00-core.conf" 'repo_path: \{\{PI_HOME\}\}/treed/printer-core' "Moonraker update component reads the canonical printer-core checkout"
Assert-Contains "moonraker/components/treed_update.py" 'TreeD-Hub/printer-core/releases' "TreeD update checks printer-core releases"
Assert-Contains "runtime-scripts/treed-update/treed-update-apply" 'TREED_UPDATE_REPO_DIR:-/home/pi/treed/printer-core' "TreeD updater defaults to the canonical printer-core checkout"
Assert-Contains "runtime-scripts/treed-update/treed-update-apply" 'treed-mainshellos\|printer-core' "TreeD updater keeps the legacy target id and accepts printer-core as an alias"
Assert-Contains "runtime-scripts/treed-update/treed-update-apply" 'treed-shell-ui\.zip' "TreeD updater can install the released UI archive"
Assert-Contains "runtime-scripts/treed-update/treed-update-apply" 'python3 -m zipfile -t' "TreeD updater validates the UI archive"
Assert-Contains "runtime-scripts/treed-update/treed-update-apply" 'ui\.previous' "TreeD updater retains a rollback UI directory"
Assert-Contains "runtime-scripts/treed-update/treed-update-apply" 'systemctl restart "\$\{SHELL_SERVICE\}"' "TreeD updater restarts the UI after an atomic publish"
Assert-Contains "runtime-scripts/README.md" 'treed-update' "runtime scripts docs include TreeD update command"

Assert-Contains "loader/steps/runtime-bootstrap.sh" 'TREED_CROWSNEST_REPO' "runtime-bootstrap exposes Crowsnest repo configuration"
Assert-Contains "loader/steps/runtime-bootstrap.sh" 'ensure_crowsnest_runtime' "runtime-bootstrap installs or updates Crowsnest runtime"
Assert-Contains "loader/steps/runtime-bootstrap.sh" 'CROWSNEST_UNATTENDED=1' "Crowsnest install runs unattended"
Assert-Contains "loader/steps/packages-core.sh" 'python3-numpy python3-matplotlib libatlas-base-dev libopenblas-dev' "packages-core installs numpy/matplotlib system dependencies"
Assert-Contains "loader/steps/packages-core.sh" 'packages_core_current\(\)' "packages-core checks package state before apt install"
Assert-Contains "loader/steps/packages-core.sh" 'core package set already current' "packages-core skips apt install when packages are current"
Assert-Contains "loader/steps/runtime-bootstrap.sh" 'ensure_klippy_numpy\(\)' "runtime-bootstrap manages numpy in klippy-env"
Assert-Contains "loader/steps/runtime-bootstrap.sh" 'klippy numpy already installed, skip' "runtime-bootstrap skips numpy install when it is already importable"
Assert-Contains "loader/steps/runtime-bootstrap.sh" "\'\$\{KLIPPY_ENV_DIR\}/bin/pip\' install numpy" "runtime-bootstrap installs latest stable numpy into klippy-env"
Assert-Contains "loader/steps/runtime-bootstrap.sh" 'ensure_klippy_matplotlib\(\)' "runtime-bootstrap manages matplotlib in klippy-env"
Assert-Contains "loader/steps/runtime-bootstrap.sh" 'klippy matplotlib already installed, skip' "runtime-bootstrap skips matplotlib install when it is already importable"
Assert-Contains "loader/steps/runtime-bootstrap.sh" "\'\$\{KLIPPY_ENV_DIR\}/bin/pip\' install matplotlib" "runtime-bootstrap installs latest stable matplotlib into klippy-env"
Assert-Contains "loader/steps/runtime-bootstrap.sh" 'systemctl daemon-reload\s+if ! systemctl cat crowsnest\.service' "runtime-bootstrap reloads systemd before validating installed crowsnest service"
Assert-Contains "loader/steps/runtime-bootstrap.sh" 'if \[ -d "\$\{CROWSNEST_DIR\}" \]; then\s+chown -R "\$\{PI_USER\}:\$\{PI_GROUP\}" "\$\{CROWSNEST_DIR\}"' "runtime-bootstrap does not chown a missing Crowsnest checkout when install is disabled"
Assert-Contains "loader/bootstrap.sh" 'export TREED_CROWSNEST_INSTALL' "bootstrap forwards Crowsnest install contract into loader steps"
Assert-Contains "loader/steps/crowsnest-webcam.sh" 'skip_webcam_deploy "crowsnest\.service is missing"' "optional camera path cleans stale webcam config when crowsnest service is missing"
Assert-Contains "loader/steps/verify.sh" 'auto: crowsnest\.service missing' "verify auto mode skips camera HTTP checks when crowsnest service is missing"
Assert-Contains "loader/README.md" 'TREED_CROWSNEST_REPO' "loader docs include top-level Crowsnest bootstrap variables"
Assert-Contains "loader/steps/README.md" 'TREED_CROWSNEST_REPO' "loader step docs include Crowsnest bootstrap variables"
Assert-NotContains "loader/steps/mainsail-web.sh" 'wget -q' "mainsail-web download is not silent"
Assert-Contains "loader/steps/mainsail-web.sh" 'TREED_MAINSAIL_WGET_TIMEOUT' "mainsail-web download has bounded timeout"
Assert-Contains "loader/steps/mainsail-web.sh" 'mainsail-web: downloading Mainsail archive' "mainsail-web logs download start"
Assert-Contains "loader/steps/mainsail-web.sh" 'mainsail-web: prepared Mainsail archive' "mainsail-web logs prepared archive size"
Assert-Contains "loader/steps/mainsail-web.sh" 'if wget' "mainsail-web handles wget failure explicitly"
Assert-Contains "loader/steps/mainsail-web.sh" 'TREED_MAINSAIL_LOCAL_ZIP' "mainsail-web supports bundled local zip"
Assert-Contains "loader/steps/mainsail-web.sh" 'TREED_MAINSAIL_PREFER_LOCAL_ZIP' "mainsail-web prefers bundled local zip by default"
Assert-Contains "loader/steps/mainsail-web.sh" 'mainsail-web: using bundled Mainsail archive' "mainsail-web logs bundled archive use"
Assert-Contains "loader/steps/mainsail-web.sh" 'TREED_MAINSAIL_ALLOW_EXISTING_FALLBACK' "mainsail-web can fall back to an existing valid web root"
Assert-Contains "loader/steps/mainsail-web.sh" 'mainsail-web: using existing valid web root' "mainsail-web logs existing web root fallback"
Assert-NotContains "loader/loader.sh" 'OPTIONAL_STEPS=\([\s\S]*"klipperscreen-install"' "KlipperScreen install is required, not best-effort"
Assert-NotContains "loader/loader.sh" 'OPTIONAL_STEPS=\([\s\S]*"klipperscreen-theme"' "KlipperScreen theme is required with managed install"
Assert-NotContains "loader/loader.sh" 'OPTIONAL_STEPS=\([\s\S]*"klipperscreen-integr"' "KlipperScreen integr is required with managed install"
Assert-Contains "loader/steps/klipperscreen-install.sh" 'klipperscreen_needs_install\(\)' "KlipperScreen install has explicit version/integrity decision"
Assert-NotContains "loader/steps/klipperscreen-install.sh" 'KlipperScreen\.service already exists, skipping install' "KlipperScreen install does not bypass version/integrity checks when service exists"
Assert-Contains "loader/steps/klipperscreen-install.sh" 'KS_HOME="\$\{KS_HOME_DEFAULT\}"' "KlipperScreen install uses normal package path by default"
Assert-Contains "loader/steps/klipperscreen-install.sh" 'KS_STAGING_PARENT="\$\(dirname "\$\{KS_STAGING_DIR\}"\)"' "KlipperScreen install prepares staging parent"
Assert-Contains "loader/steps/klipperscreen-install.sh" 'chown "\$\{PI_USER\}:\$\{PI_GROUP\}" "\$\{KS_STAGING_PARENT\}"' "KlipperScreen install gives staging parent to deploy user"
Assert-Contains "loader/steps/klipperscreen-install.sh" 's\|sudo \|\|g' "KlipperScreen installer strips internal sudo for root-managed install"
Assert-Contains "loader/steps/klipperscreen-install.sh" 'USER="\$\{PI_USER\}"' "KlipperScreen installer runs with deploy user identity"
Assert-Contains "loader/steps/klipperscreen-install.sh" 'HOME="\$\{PI_HOME\}"' "KlipperScreen installer runs with deploy user home"
Assert-Contains "loader/steps/klipperscreen-install.sh" 'KLIPPERSCREEN_VENV="\$\{KS_ENV\}"' "KlipperScreen installer pins venv path under deploy home"
Assert-Contains "loader/steps/klipperscreen-install.sh" 'chown -R "\$\{PI_USER\}:\$\{PI_GROUP\}" "\$\{KS_HOME\}"' "KlipperScreen install returns package ownership to deploy user"
Assert-Contains "loader/steps/klipperscreen-install.sh" 'chown -R "\$\{PI_USER\}:\$\{PI_GROUP\}" "\$\{KS_ENV\}"' "KlipperScreen install returns venv ownership to deploy user"
Assert-Contains "loader/steps/klipperscreen-install.sh" '\[ ! -x "\$\{KS_ENV\}/bin/python" \]' "KlipperScreen install detects missing runtime venv"
Assert-Contains "loader/steps/klipperscreen-install.sh" 'KLIPPERSCREEN_INSTALL_REASON="runtime-incomplete"' "KlipperScreen install repairs partial runtime installs"
Assert-Contains "loader/steps/klipperscreen-install.sh" 'merge-base --is-ancestor "\$\{target_commit\}" "\$\{installed_head\}"' "KlipperScreen install treats installed descendant as same-or-newer"
Assert-Contains "loader/steps/klipperscreen-install.sh" 'journalctl -u "\$\{unit\}" -n' "KlipperScreen install prints journal diagnostics on service failure"
Assert-Contains "loader/steps/klipperscreen-theme.sh" 'log_error "klipperscreen-theme: styles dir not found' "KlipperScreen theme fails fast when managed install is incomplete"
Assert-Contains "loader/steps/klipperscreen-integr.sh" 'journalctl -u "\$\{unit\}" -n' "KlipperScreen integr prints journal diagnostics on service failure"
Assert-Contains "loader/steps/klipper-anti-shutdown.sh" 'wait_klippy_state' "Klipper anti-shutdown waits for terminal state before deciding"
Assert-Contains "loader/steps/klipper-anti-shutdown.sh" 'state_message.*shutdown' "Klipper anti-shutdown classifies shutdown from state_message"
Assert-Contains "loader/steps/check-env.sh" 'TREED_EBB_CANBUS_UUID is required' "check-env fails fast when EBB UUID is missing"
Assert-NotContains "loader/steps/check-env.sh" 'will try auto-detect via canbus_query' "check-env does not allow EBB UUID auto-detect"
Assert-Contains "loader/bootstrap.sh" 'TREED_MAIN_MCU_CANBUS_UUID:=d372e54bf965' "bootstrap defaults to the detected Octopus CAN UUID"
Assert-Contains "loader/bootstrap.sh" 'TREED_KLIPPER_PREFLIGHT_CAN_UUIDS_REQUIRED:=0' "bootstrap makes CAN UUID preflight diagnostic by default"
Assert-Contains "loader/bootstrap.sh" 'TREED_EBB_CANBUS_UUID:=efaf957ab20f' "bootstrap defaults to the detected EBB UUID"
Assert-Contains "loader/bootstrap.sh" 'TREED_EDDY_ENABLED:=1' "bootstrap enables Eddy by default for V2"
Assert-Contains "loader/bootstrap.sh" 'TREED_EDDY_CANBUS_UUID:=95485b93332a' "bootstrap defaults to the detected Eddy UUID"
Assert-Contains "loader/steps/check-env.sh" 'TREED_EBB_CANBUS_UUID:-efaf957ab20f' "check-env defaults to the detected EBB UUID"
Assert-Contains "loader/steps/check-env.sh" 'TREED_EDDY_ENABLED:-1' "check-env treats Eddy as enabled by default"
Assert-Contains "loader/steps/check-env.sh" 'TREED_EDDY_CANBUS_UUID:-95485b93332a' "check-env defaults to the detected Eddy UUID"
Assert-Contains "loader/steps/check-env.sh" 'TREED_MAIN_MCU_CANBUS_UUID:-d372e54bf965' "check-env defaults to the detected Octopus CAN UUID"
Assert-Contains "loader/steps/check-env.sh" 'TREED_KLIPPER_PREFLIGHT_CAN_UUIDS_REQUIRED:-0' "check-env defaults CAN UUID preflight to non-blocking"
Assert-Contains "loader/steps/check-env.sh" "TREED_MAIN_MCU_PROFILE_UUID=`"${MainMcuProfileUuid}`"" "check-env locks main MCU UUID to active Klipper profile"
Assert-Contains "loader/steps/check-env.sh" "TREED_EBB_PROFILE_UUID=`"${EbbProfileUuid}`"" "check-env locks EBB UUID to active Klipper profile"
Assert-Contains "loader/steps/check-env.sh" "TREED_EDDY_PROFILE_UUID=`"${EddyProfileUuid}`"" "check-env locks Eddy UUID to active Klipper profile"
Assert-Contains "loader/steps/check-env.sh" "TREED_CAN_PROFILE_IFACE=`"${MainMcuProfileIface}`"" "check-env locks CAN interface to active Klipper profile"
Assert-Contains "loader/steps/check-env.sh" "TREED_EDDY_PROFILE_IFACE=`"${EddyProfileIface}`"" "check-env checks Eddy profile CAN interface"
Assert-Contains "loader/steps/check-env.sh" 'profile_locked_value_check\(\)' "check-env rejects hardware env values that do not match static profile cfg"
Assert-Contains "loader/steps/check-env.sh" 'TREED_EDDY_ENABLED=0 is unsupported by treed_v2_corexy_v1' "check-env rejects false Eddy optionality"
Assert-NotContains "loader/loader.sh" "`"$RemovedProfileStep`"" "profile-mutating step removed from install pipeline"
Assert-Contains "loader/steps/runtime-bootstrap.sh" 'CAN UUID readiness is diagnostic' "runtime preflight documents non-blocking CAN UUID readiness"
Assert-Contains "loader/steps/runtime-bootstrap.sh" 'TREED_KLIPPER_PREFLIGHT_CAN_UUIDS_REQUIRED' "runtime preflight exposes strict CAN UUID gate"
Assert-Contains "loader/steps/runtime-bootstrap.sh" 'CAN UUID readiness check unavailable' "runtime preflight does not block when diagnostic query tooling is unavailable"
Assert-Contains "loader/steps/runtime-bootstrap.sh" 'CAN interface is missing .*non-blocking' "runtime preflight does not block on CAN interface in diagnostic mode"
Assert-Contains "loader/steps/runtime-bootstrap.sh" 'TREED_EDDY_ENABLED=0 is unsupported by treed_v2_corexy_v1' "runtime preflight rejects false Eddy optionality"
Assert-Contains "loader/steps/maintenance-start.sh" 'journalctl -u "\$\{unit\}" -n 120' "maintenance-start prints recent journal on required service start failure"
Assert-Contains "loader/loader.sh" 'TREED_STATE_FILE="/run/treed-loader/state\.env"' "loader writes state snapshot to /run/treed-loader/state.env"
Assert-Contains "loader/loader.sh" 'detect_device_state\(\)' "loader has device state detector"
Assert-Contains "loader/loader.sh" 'TREED_DEVICE_STATE="fresh"' "loader can classify a fresh device"
Assert-Contains "loader/loader.sh" 'TREED_DEVICE_STATE="recover"' "loader can classify a recovery device"
Assert-Contains "loader/loader.sh" 'fresh\)[\s\S]*effective_mode="clean"' "auto deploy maps fresh state to clean"
Assert-Contains "loader/loader.sh" 'update\|recover\)[\s\S]*effective_mode="preserve"' "auto deploy maps update/recover state to preserve"
Assert-Contains "loader/loader.sh" 'TREED_LOADER_MODE="\$\{TREED_LOADER_MODE:-apply\}"' "loader exposes apply/check mode"
Assert-Contains "loader/loader.sh" 'apply\|check' "loader validates apply/check mode"
Assert-Contains "loader/loader.sh" 'run_check_mode\(\)' "loader has a read-only actuality check mode"
Assert-Contains "loader/loader.sh" 'TREED_CAM_RESOLUTION:-1920x1080' "loader check mode uses the camera resolution default"
Assert-Contains "loader/loader.sh" 'TREED_CAM_FPS:-30' "loader check mode uses the camera FPS default"
Assert-Contains "loader/loader.sh" 'check_config_value "crowsnest max FPS"[^\r\n]+"max_fps"' "loader check mode detects Crowsnest FPS drift"
Assert-Contains "loader/loader.sh" 'check_config_value "crowsnest ustreamer flags"[^\r\n]+"custom_flags"' "loader check mode detects Crowsnest ustreamer flag drift"
Assert-Contains "loader/loader.sh" 'check_config_value "Moonraker webcam target FPS"[^\r\n]+"target_fps"' "loader check mode detects Moonraker webcam FPS drift"
Assert-Contains "loader/steps/crowsnest-webcam.sh" 'CAM_FPS="\$\{TREED_CAM_FPS:-30\}"' "camera deployment keeps the 30 FPS default override"
Assert-Contains "loader/steps/crowsnest-webcam.sh" 'CAM_FORMAT="\$\{TREED_CAM_FORMAT:-MJPEG\}"' "camera deployment keeps the MJPEG format default override"
Assert-Contains "loader/steps/crowsnest-webcam.sh" 'CAM_ENCODER="\$\{TREED_CAM_ENCODER:-HW\}"' "camera deployment keeps the hardware encoder default override"
Assert-Contains "loader/steps/crowsnest-webcam.sh" 'max_fps: \$\{CAM_FPS\}' "camera deployment writes max_fps from the shared FPS value"
Assert-Contains "loader/steps/crowsnest-webcam.sh" 'custom_flags: \$\{CAM_USTREAMER_CUSTOM_FLAGS\}' "camera deployment writes ustreamer custom flags"
Assert-Contains "loader/steps/crowsnest-webcam.sh" 'target_fps: \$\{CAM_FPS\}' "camera deployment writes target_fps from the shared FPS value"
Assert-Contains "loader/loader.sh" 'if \[ "\$\{TREED_LOADER_MODE\}" != "check" \] && \[ -d "\$\{REPO_DIR\}/loader" \]' "loader check mode skips shell-file normalization writes"
Assert-Contains "loader/bootstrap.sh" 'if \[ "\$\{TREED_LOADER_MODE\}" != "check" \] && \[ -d "\$\{REPO_DIR\}/loader" \]' "bootstrap check mode skips shell-file normalization writes"
Assert-NotContains "loader/loader.sh" '"detect-boot-env"' "detect-boot-env is not duplicated in the main apply pipeline"
Assert-Contains "loader/loader.sh" 'TREED_CAMERA_REQUIRED:-0\}" = "1" \][\s\S]*return 1' "crowsnest-webcam becomes required when camera is required"
Assert-Contains "loader/steps/runtime-bootstrap.sh" 'CAN UUID strict gate skipped' "runtime preflight skips CAN UUID query in normal mode"
Assert-Contains "loader/steps/runtime-bootstrap.sh" 'TREED_CAMERA_REQUIRED' "runtime-bootstrap uses camera required flag for Crowsnest strictness"
Assert-Contains "loader/bootstrap.sh" 'TREED_KLIPPER_START_REQUIRE_ACTIVE:=1' "bootstrap requires Klipper active by default"
Assert-Contains "loader/steps/maintenance-start.sh" 'TREED_KLIPPER_START_REQUIRE_ACTIVE="\$\{TREED_KLIPPER_START_REQUIRE_ACTIVE:-1\}"' "maintenance-start requires Klipper active by default"
Assert-Contains "loader/steps/verify.sh" 'camera_checks_reason="required by TREED_CAMERA_REQUIRED=1"' "verify forces camera checks when camera is required"
Assert-Contains "loader/steps/verify.sh" 'VERIFY_DIAGNOSTIC_FAILS' "verify separates diagnostic failures from fatal failures"
Assert-Contains "loader/steps/verify.sh" 'klipper_can_mcus_connected_check "klipper CAN MCU connectivity"' "verify checks CAN MCU connectivity via Moonraker objects API"
Assert-Contains "loader/steps/verify.sh" 'printer/objects/list' "verify reads printer object list before CAN MCU status checks"
Assert-Contains "loader/steps/verify.sh" 'printer/objects/query' "verify queries explicit MCU status objects"
Assert-NotContains "loader/steps/verify.sh" $RemovedConfigVerifyToggle "verify has no runtime config validation toggle"
Assert-Contains "bootstrap-pi.sh" 'TREED_DEPLOY_MODE=auto TREED_NONINTERACTIVE=1 bash install\.sh' "Pi bootstrap runs installer in auto mode"
Assert-Contains "bootstrap-pi.sh" 'TREED_DEVICE_STATE=fresh' "Pi bootstrap reboots only after fresh install"
Assert-Contains "bootstrap-pi.sh" 'RUN_HOME="\$\(getent passwd "\$\{RUN_USER\}" \| cut -d: -f6 \|\| true\)"' "Pi bootstrap resolves deploy user home"
Assert-Contains "bootstrap-pi.sh" 'BASE="\$\{BASE:-\$\{RUN_HOME\}/treed\}"' "Pi bootstrap defaults installer checkout under deploy user home"
Assert-NotContains "bootstrap-pi.sh" 'BASE="\$\{BASE:-/home/pi/treed\}"' "Pi bootstrap does not hard-code /home/pi for non-pi users"
Assert-Contains "loader/steps/treed-shell-install.sh" 'TREED_SHELL_RELEASE_API_URL' "TreeD Shell install uses release API contract"
Assert-Contains "loader/steps/treed-shell-install.sh" 'treed-shell-ui\.zip' "TreeD Shell install uses the production UI archive asset"
Assert-Contains "loader/steps/treed-shell-install.sh" 'python3 -m zipfile -t' "TreeD Shell install validates the UI archive before publish"
Assert-Contains "loader/steps/treed-shell-install.sh" 'python3 -m http\.server' "TreeD Shell service serves the unpacked UI bundle locally"
Assert-Contains "loader/steps/treed-shell-install.sh" 'TREED_SHELL_WEB_DIR must be inside' "TreeD Shell install guards destructive web dir replacement"
Assert-Contains "runtime-scripts/treed-ui/treed-ui" 'systemctl reset-failed KlipperScreen\.service' "TreeD UI switch clears stale KlipperScreen failed state when TS is selected"
Assert-Contains "loader/steps/treed-shell-install.sh" 'apt_get_noninteractive install unclutter' "TreeD Shell install attempts optional unclutter package install"
Assert-Contains "loader/steps/treed-shell-install.sh" 'command -v unclutter' "TreeD Shell kiosk launcher starts unclutter only when available"
Assert-Contains "loader/steps/treed-shell-install.sh" 'TREED_SHELL_CHROMIUM_RENDERING:-hardware' "TreeD Shell kiosk defaults Chromium rendering mode to hardware"
Assert-Contains "loader/steps/treed-shell-install.sh" 'TREED_SHELL_WINDOW_SIZE:-960,544' "TreeD Shell kiosk defaults to the printer screen window size"
Assert-Contains "loader/steps/treed-shell-install.sh" 'TREED_SHELL_WINDOW_POSITION:-0,0' "TreeD Shell kiosk pins Chromium to the screen origin"
Assert-Contains "loader/steps/treed-shell-install.sh" 'TREED_SHELL_DEVICE_SCALE_FACTOR:-1' "TreeD Shell kiosk uses 1:1 Chromium device scaling by default"
Assert-Contains "loader/steps/treed-shell-install.sh" '--window-size=' "TreeD Shell kiosk passes explicit Chromium window size"
Assert-Contains "loader/steps/treed-shell-install.sh" '--window-position=' "TreeD Shell kiosk passes explicit Chromium window position"
Assert-Contains "loader/steps/treed-shell-install.sh" '--force-device-scale-factor=' "TreeD Shell kiosk forces Chromium device scale factor"
Assert-Contains "loader/steps/treed-shell-install.sh" '--disable-pinch' "TreeD Shell kiosk disables Chromium pinch zoom"
Assert-Contains "loader/steps/treed-shell-install.sh" '--overscroll-history-navigation=0' "TreeD Shell kiosk disables touch overscroll navigation"
Assert-Contains "loader/steps/treed-shell-install.sh" 'xsetroot -cursor' "TreeD Shell kiosk sets a blank root cursor like KlipperScreen"
Assert-Contains "loader/steps/treed-shell-install.sh" 'libFLAC\.so\.8' "TreeD Shell kiosk preserves Chromium bundled library lookup for direct chromium-bin"
Assert-Contains "loader/steps/treed-shell-install.sh" 'LD_LIBRARY_PATH' "TreeD Shell kiosk exports Chromium bundled library path when needed"
Assert-Contains "loader/steps/treed-shell-install.sh" 'software\)[\s\S]*--disable-gpu[\s\S]*--enable-unsafe-swiftshader' "TreeD Shell kiosk software rendering mode disables GPU and enables software rendering"
Assert-Contains "loader/steps/treed-shell-install.sh" '--disable-background-networking' "TreeD Shell kiosk suppresses unnecessary Chromium background integrations"
Assert-Contains "loader/steps/README.md" 'TREED_SHELL_CHROMIUM_RENDERING' "loader step docs describe Chromium rendering mode"
Assert-Contains "loader/steps/README.md" 'TREED_SHELL_WINDOW_SIZE' "loader step docs describe kiosk window size override"
Assert-Contains "loader/steps/README.md" 'TREED_SHELL_WINDOW_POSITION' "loader step docs describe kiosk window position override"
Assert-Contains "loader/steps/README.md" 'TREED_SHELL_DEVICE_SCALE_FACTOR' "loader step docs describe kiosk scale factor override"
Assert-Contains "loader/README.md" 'TREED_SHELL_CHROMIUM_RENDERING' "loader docs describe Chromium rendering mode"
Assert-Contains "loader/README.md" 'TREED_SHELL_WINDOW_SIZE' "loader docs describe kiosk window size override"
Assert-Contains "loader/README.md" 'TREED_SHELL_WINDOW_POSITION' "loader docs describe kiosk window position override"
Assert-Contains "loader/README.md" 'TREED_SHELL_DEVICE_SCALE_FACTOR' "loader docs describe kiosk scale factor override"
Assert-NotContains "loader/steps/treed-shell-install.sh" 'npm ci' "TreeD Shell install does not install npm dependencies on the printer"
Assert-NotContains "loader/steps/treed-shell-install.sh" 'tauri:build:printer' "TreeD Shell install does not build Tauri on the printer"
Assert-Contains "loader/steps/firmware-build.sh" 'TREED_EDDY_ENABLED="\$\{TREED_EDDY_ENABLED:-1\}"' "firmware-build includes Eddy by default"
Assert-Contains "loader/steps/firmware-build.sh" 'TREED_EDDY_ENABLED=0 is unsupported by treed_v2_corexy_v1' "firmware-build rejects false Eddy optionality"
Assert-NotContains "loader/steps/firmware-build.sh" 'target=eddy_can status=skipped' "firmware-build never skips Eddy for the active Klipper profile"
Assert-Contains "loader/steps/firmware-build.sh" 'firmware_inputs_current\(\)' "firmware-build checks input signature before rebuilding"
Assert-Contains "loader/steps/firmware-build.sh" 'inputs.env' "firmware-build records input signature"
Assert-Contains "loader/steps/firmware-build.sh" 'firmware-build: existing artifacts match current inputs, skipping rebuild' "firmware-build skips rebuild when artifacts are current"
Assert-Contains "loader/steps/plymouth-initramfs-config.sh" 'OK \(extlinux backend, no config\.txt rewrite\)' "Plymouth initramfs config logs extlinux backend accurately"
Assert-Contains "loader/steps/crowsnest-webcam.sh" 'if \[ -f "\$\{MOONRAKER_ASVC\}" \]; then\s+chown "\$\{PI_USER\}:\$\{grp\}" "\$\{MOONRAKER_ASVC\}"' "Crowsnest webcam only chowns moonraker.asvc when it exists"
Assert-Contains "loader/README.md" 'TREED_LOADER_MODE' "loader docs describe apply/check mode"
Assert-Contains "loader/steps/README.md" 'TREED_LOADER_MODE' "loader step docs describe apply/check mode"

Write-Output "PASS: loader contracts"
