"""
MOONRAKER COMPONENT: TREED FILAMENT SENSOR
==========================================
Назначение:
- Публикует настройки BTT SFS V2.0 для TreeD Shell.
- Атомарно меняет только разрешенный уровень detection_length.
Контур:
- required для изменения чувствительности;
- fail-closed во время активной печати и при недоступном Klippy.
"""

from __future__ import annotations

# Блок 1: Импорты, типы и фиксированный enum уровней.
import os
from pathlib import Path
import re
import tempfile
from typing import Any, Dict, Mapping, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from ..confighelper import ConfigHelper

SENSITIVITY_MM = {
    "high": 7.0,
    "medium": 15.0,
    "low": 25.0,
}
SETTINGS_ENDPOINT = "/server/treed/filament-sensor/settings"
RUNTIME_OBJECTS: Mapping[str, Optional[list[str]]] = {
    "print_stats": ["state"],
    "gcode_macro FILAMENT_SENSOR_STATUS": ["mode"],
    "filament_switch_sensor filament_switch": ["enabled", "filament_detected"],
    "filament_motion_sensor filament_motion": ["enabled", "filament_detected"],
}


class TreeDFilamentSensor:
    def __init__(self, config: ConfigHelper) -> None:
        # Блок 2: Runtime-зависимости и единый GET/POST endpoint.
        self.server = config.get_server()
        self.klippy_apis = self.server.lookup_component("klippy_apis")
        self.config_path = Path(config.get("config_path"))
        self.restart_required = False
        self.server.register_endpoint(
            SETTINGS_ENDPOINT,
            ["GET", "POST"],
            self._handle_settings,
            wrap_result=False,
        )

    async def _handle_settings(self, web_request: object) -> Dict[str, Any]:
        # Блок 3: GET читает runtime, POST валидирует enum и print guard.
        action = str(getattr(web_request, "get_action")()).upper()
        if action == "GET":
            return await self._read_status()
        if action != "POST":
            raise self.server.error("unsupported request type", 405)

        sensitivity = str(getattr(web_request, "get_str")("sensitivity")).strip().lower()
        if sensitivity not in SENSITIVITY_MM:
            allowed = ", ".join(SENSITIVITY_MM)
            raise self.server.error(f"sensitivity must be one of: {allowed}")

        objects = await self._query_runtime()
        print_state = str(objects.get("print_stats", {}).get("state", "")).lower()
        if print_state in {"printing", "paused"}:
            raise self.server.error("filament sensitivity is unavailable during active print", 409)

        _atomic_write(self.config_path, _render_runtime_config(sensitivity))
        self.restart_required = True
        try:
            await self.klippy_apis.do_restart("RESTART")
        except Exception:
            raise
        else:
            self.restart_required = False

        status = _status_from_objects(objects, sensitivity, self.restart_required)
        status["message"] = "Klipper restart requested"
        return status

    async def _read_status(self) -> Dict[str, Any]:
        # Блок 4: Ошибки Klippy/config остаются явным unavailable-состоянием.
        try:
            sensitivity = _read_sensitivity(self.config_path)
            objects = await self._query_runtime()
        except Exception as error:
            return _unavailable_status(str(error), self.restart_required)
        return _status_from_objects(objects, sensitivity, self.restart_required)

    async def _query_runtime(self) -> Dict[str, Any]:
        objects = await self.klippy_apis.query_objects(RUNTIME_OBJECTS, default={})
        if not isinstance(objects, dict) or not objects:
            raise self.server.error("Klippy filament sensor state is unavailable", 503)
        return objects


# Блок 5: Pure helpers для config и response contract.
def _render_runtime_config(sensitivity: str) -> str:
    detection_length = SENSITIVITY_MM[sensitivity]
    return (
        "# Runtime-generated by treed_filament_sensor.py.\n"
        "# Edit through /server/treed/filament-sensor/settings only.\n"
        "[gcode_macro _FILAMENT_SENSOR_SENSITIVITY_STATE]\n"
        "description: \"Filament sensor: configured encoder sensitivity\"\n"
        f"variable_sensitivity: \"{sensitivity}\"\n"
        "gcode:\n\n"
        "[filament_motion_sensor filament_motion]\n"
        "switch_pin: PG12\n"
        f"detection_length: {detection_length:.1f}\n"
        "extruder: extruder\n"
        "pause_on_runout: False\n"
        "event_delay: 3.0\n"
        "pause_delay: 0.5\n\n"
        "runout_gcode:\n"
        "  _TREED_FILAMENT_RUNOUT_PAUSE SOURCE=filament_motion MSG=\"Filament encoder runout: no filament motion\"\n\n"
        "insert_gcode:\n"
        "  RESPOND PREFIX=\"filament\" MSG=\"Filament encoder signal restored\"\n"
    )


def _read_sensitivity(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"(?m)^detection_length:\s*([0-9]+(?:\.[0-9]+)?)\s*$", text)
    if match is None:
        raise ValueError("filament motion config has no detection_length")
    value = float(match.group(1))
    for sensitivity, expected in SENSITIVITY_MM.items():
        if abs(value - expected) < 0.001:
            return sensitivity
    raise ValueError(f"unsupported detection_length: {value:g}")


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    file_descriptor, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent, text=True)
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temp_name, 0o644)
        os.replace(temp_name, path)
    finally:
        if os.path.exists(temp_name):
            os.unlink(temp_name)


def _status_from_objects(
    objects: Mapping[str, Any],
    sensitivity: str,
    restart_required: bool,
) -> Dict[str, Any]:
    switch = objects.get("filament_switch_sensor filament_switch")
    motion = objects.get("filament_motion_sensor filament_motion")
    macro = objects.get("gcode_macro FILAMENT_SENSOR_STATUS")
    available = isinstance(switch, dict)
    mode = str(macro.get("mode", "presence")).lower() if isinstance(macro, dict) else "presence"
    if mode not in {"presence", "motion"}:
        mode = "presence"
    return {
        "available": available,
        "mode": mode,
        "sensitivity": sensitivity,
        "presenceDetected": _optional_bool(switch, "filament_detected"),
        "switchEnabled": _optional_bool(switch, "enabled") is True,
        "motionEnabled": _optional_bool(motion, "enabled") is True,
        "restartRequired": restart_required,
        "message": None if available else "filament_switch is unavailable",
    }


def _optional_bool(value: Any, key: str) -> Optional[bool]:
    if not isinstance(value, dict) or not isinstance(value.get(key), bool):
        return None
    return value[key]


def _unavailable_status(message: str, restart_required: bool) -> Dict[str, Any]:
    return {
        "available": False,
        "mode": "presence",
        "sensitivity": "medium",
        "presenceDetected": None,
        "switchEnabled": False,
        "motionEnabled": False,
        "restartRequired": restart_required,
        "message": message,
    }


def load_component(config: ConfigHelper) -> TreeDFilamentSensor:
    return TreeDFilamentSensor(config)
